# Generated by Django 4.2.4 on 2023-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='startingBid',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
