# Generated by Django 4.2.4 on 2023-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('TO', 'Toys'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
