# Generated by Django 4.2.4 on 2023-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('FA', 'Fashion'), ('FU', 'Furniture'), ('TO', 'Toys'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
