# Generated by Django 4.2.4 on 2023-09-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='relatedListing',
        ),
    ]
