# Generated by Django 4.2.4 on 2023-09-14 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commentedListing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingsComments', to='auctions.listing')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
