# Generated by Django 4.2.4 on 2023-09-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_bid_winning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winning',
        ),
    ]
