# Generated by Django 4.2.4 on 2023-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_listing_winning_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winning_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
